/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.xml]'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.txt]'
import { Route as RegulaminRouteImport } from './routes/regulamin'
import { Route as PolitykaPrywatnosciRouteImport } from './routes/polityka-prywatnosci'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as SurveyTokenRouteImport } from './routes/survey/$token'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as SurveyTokenIndexRouteImport } from './routes/survey/$token.index'
import { Route as SurveyTokenSuccessRouteImport } from './routes/survey/$token.success'
import { Route as BlogPreviewTokenRouteImport } from './routes/blog/preview.$token'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RegulaminRoute = RegulaminRouteImport.update({
  id: '/regulamin',
  path: '/regulamin',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitykaPrywatnosciRoute = PolitykaPrywatnosciRouteImport.update({
  id: '/polityka-prywatnosci',
  path: '/polityka-prywatnosci',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const SurveyTokenRoute = SurveyTokenRouteImport.update({
  id: '/survey/$token',
  path: '/survey/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const SurveyTokenIndexRoute = SurveyTokenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SurveyTokenRoute,
} as any)
const SurveyTokenSuccessRoute = SurveyTokenSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => SurveyTokenRoute,
} as any)
const BlogPreviewTokenRoute = BlogPreviewTokenRouteImport.update({
  id: '/preview/$token',
  path: '/preview/$token',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/polityka-prywatnosci': typeof PolitykaPrywatnosciRoute
  '/regulamin': typeof RegulaminRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/survey/$token': typeof SurveyTokenRouteWithChildren
  '/blog/': typeof BlogIndexRoute
  '/blog/preview/$token': typeof BlogPreviewTokenRoute
  '/survey/$token/success': typeof SurveyTokenSuccessRoute
  '/survey/$token/': typeof SurveyTokenIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/polityka-prywatnosci': typeof PolitykaPrywatnosciRoute
  '/regulamin': typeof RegulaminRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
  '/blog/preview/$token': typeof BlogPreviewTokenRoute
  '/survey/$token/success': typeof SurveyTokenSuccessRoute
  '/survey/$token': typeof SurveyTokenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/polityka-prywatnosci': typeof PolitykaPrywatnosciRoute
  '/regulamin': typeof RegulaminRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/survey/$token': typeof SurveyTokenRouteWithChildren
  '/blog/': typeof BlogIndexRoute
  '/blog/preview/$token': typeof BlogPreviewTokenRoute
  '/survey/$token/success': typeof SurveyTokenSuccessRoute
  '/survey/$token/': typeof SurveyTokenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/polityka-prywatnosci'
    | '/regulamin'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/survey/$token'
    | '/blog/'
    | '/blog/preview/$token'
    | '/survey/$token/success'
    | '/survey/$token/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/polityka-prywatnosci'
    | '/regulamin'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/blog'
    | '/blog/preview/$token'
    | '/survey/$token/success'
    | '/survey/$token'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/polityka-prywatnosci'
    | '/regulamin'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/survey/$token'
    | '/blog/'
    | '/blog/preview/$token'
    | '/survey/$token/success'
    | '/survey/$token/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRouteWithChildren
  PolitykaPrywatnosciRoute: typeof PolitykaPrywatnosciRoute
  RegulaminRoute: typeof RegulaminRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SurveyTokenRoute: typeof SurveyTokenRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regulamin': {
      id: '/regulamin'
      path: '/regulamin'
      fullPath: '/regulamin'
      preLoaderRoute: typeof RegulaminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polityka-prywatnosci': {
      id: '/polityka-prywatnosci'
      path: '/polityka-prywatnosci'
      fullPath: '/polityka-prywatnosci'
      preLoaderRoute: typeof PolitykaPrywatnosciRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/survey/$token': {
      id: '/survey/$token'
      path: '/survey/$token'
      fullPath: '/survey/$token'
      preLoaderRoute: typeof SurveyTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/survey/$token/': {
      id: '/survey/$token/'
      path: '/'
      fullPath: '/survey/$token/'
      preLoaderRoute: typeof SurveyTokenIndexRouteImport
      parentRoute: typeof SurveyTokenRoute
    }
    '/survey/$token/success': {
      id: '/survey/$token/success'
      path: '/success'
      fullPath: '/survey/$token/success'
      preLoaderRoute: typeof SurveyTokenSuccessRouteImport
      parentRoute: typeof SurveyTokenRoute
    }
    '/blog/preview/$token': {
      id: '/blog/preview/$token'
      path: '/preview/$token'
      fullPath: '/blog/preview/$token'
      preLoaderRoute: typeof BlogPreviewTokenRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  BlogPreviewTokenRoute: typeof BlogPreviewTokenRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  BlogPreviewTokenRoute: BlogPreviewTokenRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface SurveyTokenRouteChildren {
  SurveyTokenSuccessRoute: typeof SurveyTokenSuccessRoute
  SurveyTokenIndexRoute: typeof SurveyTokenIndexRoute
}

const SurveyTokenRouteChildren: SurveyTokenRouteChildren = {
  SurveyTokenSuccessRoute: SurveyTokenSuccessRoute,
  SurveyTokenIndexRoute: SurveyTokenIndexRoute,
}

const SurveyTokenRouteWithChildren = SurveyTokenRoute._addFileChildren(
  SurveyTokenRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRouteWithChildren,
  PolitykaPrywatnosciRoute: PolitykaPrywatnosciRoute,
  RegulaminRoute: RegulaminRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SurveyTokenRoute: SurveyTokenRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
