// This file will be generated by Supabase CLI: npm run generate-types
// For now, placeholder types

export interface Database {
  public: {
    Tables: {
      tenants: {
        Row: {
          id: string
          name: string
          email: string
          domain: string | null
          subscription_status: 'trial' | 'active' | 'cancelled'
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          email: string
          domain?: string | null
          subscription_status?: 'trial' | 'active' | 'cancelled'
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          email?: string
          domain?: string | null
          subscription_status?: 'trial' | 'active' | 'cancelled'
          created_at?: string
          updated_at?: string
        }
      }
      // More tables will be added after running migrations
    }
    Views: {}
    Functions: {}
    Enums: {}
  }
}
