/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminSurveysIndexRouteImport } from './routes/admin/surveys/index'
import { Route as AdminResponsesIndexRouteImport } from './routes/admin/responses/index'
import { Route as AdminIntakeIndexRouteImport } from './routes/admin/intake/index'
import { Route as AdminSurveysNewRouteImport } from './routes/admin/surveys/new'
import { Route as AdminSurveysSurveyIdRouteImport } from './routes/admin/surveys/$surveyId'
import { Route as AdminResponsesResponseIdRouteImport } from './routes/admin/responses/$responseId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSurveysIndexRoute = AdminSurveysIndexRouteImport.update({
  id: '/surveys/',
  path: '/surveys/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResponsesIndexRoute = AdminResponsesIndexRouteImport.update({
  id: '/responses/',
  path: '/responses/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIntakeIndexRoute = AdminIntakeIndexRouteImport.update({
  id: '/intake/',
  path: '/intake/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSurveysNewRoute = AdminSurveysNewRouteImport.update({
  id: '/surveys/new',
  path: '/surveys/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSurveysSurveyIdRoute = AdminSurveysSurveyIdRouteImport.update({
  id: '/surveys/$surveyId',
  path: '/surveys/$surveyId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResponsesResponseIdRoute =
  AdminResponsesResponseIdRouteImport.update({
    id: '/responses/$responseId',
    path: '/responses/$responseId',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/responses/$responseId': typeof AdminResponsesResponseIdRoute
  '/admin/surveys/$surveyId': typeof AdminSurveysSurveyIdRoute
  '/admin/surveys/new': typeof AdminSurveysNewRoute
  '/admin/intake/': typeof AdminIntakeIndexRoute
  '/admin/responses/': typeof AdminResponsesIndexRoute
  '/admin/surveys/': typeof AdminSurveysIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AdminIndexRoute
  '/admin/responses/$responseId': typeof AdminResponsesResponseIdRoute
  '/admin/surveys/$surveyId': typeof AdminSurveysSurveyIdRoute
  '/admin/surveys/new': typeof AdminSurveysNewRoute
  '/admin/intake': typeof AdminIntakeIndexRoute
  '/admin/responses': typeof AdminResponsesIndexRoute
  '/admin/surveys': typeof AdminSurveysIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/responses/$responseId': typeof AdminResponsesResponseIdRoute
  '/admin/surveys/$surveyId': typeof AdminSurveysSurveyIdRoute
  '/admin/surveys/new': typeof AdminSurveysNewRoute
  '/admin/intake/': typeof AdminIntakeIndexRoute
  '/admin/responses/': typeof AdminResponsesIndexRoute
  '/admin/surveys/': typeof AdminSurveysIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/admin/'
    | '/admin/responses/$responseId'
    | '/admin/surveys/$surveyId'
    | '/admin/surveys/new'
    | '/admin/intake/'
    | '/admin/responses/'
    | '/admin/surveys/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin'
    | '/admin/responses/$responseId'
    | '/admin/surveys/$surveyId'
    | '/admin/surveys/new'
    | '/admin/intake'
    | '/admin/responses'
    | '/admin/surveys'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/admin/'
    | '/admin/responses/$responseId'
    | '/admin/surveys/$surveyId'
    | '/admin/surveys/new'
    | '/admin/intake/'
    | '/admin/responses/'
    | '/admin/surveys/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/surveys/': {
      id: '/admin/surveys/'
      path: '/surveys'
      fullPath: '/admin/surveys/'
      preLoaderRoute: typeof AdminSurveysIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/responses/': {
      id: '/admin/responses/'
      path: '/responses'
      fullPath: '/admin/responses/'
      preLoaderRoute: typeof AdminResponsesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/intake/': {
      id: '/admin/intake/'
      path: '/intake'
      fullPath: '/admin/intake/'
      preLoaderRoute: typeof AdminIntakeIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/surveys/new': {
      id: '/admin/surveys/new'
      path: '/surveys/new'
      fullPath: '/admin/surveys/new'
      preLoaderRoute: typeof AdminSurveysNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/surveys/$surveyId': {
      id: '/admin/surveys/$surveyId'
      path: '/surveys/$surveyId'
      fullPath: '/admin/surveys/$surveyId'
      preLoaderRoute: typeof AdminSurveysSurveyIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/responses/$responseId': {
      id: '/admin/responses/$responseId'
      path: '/responses/$responseId'
      fullPath: '/admin/responses/$responseId'
      preLoaderRoute: typeof AdminResponsesResponseIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminResponsesResponseIdRoute: typeof AdminResponsesResponseIdRoute
  AdminSurveysSurveyIdRoute: typeof AdminSurveysSurveyIdRoute
  AdminSurveysNewRoute: typeof AdminSurveysNewRoute
  AdminIntakeIndexRoute: typeof AdminIntakeIndexRoute
  AdminResponsesIndexRoute: typeof AdminResponsesIndexRoute
  AdminSurveysIndexRoute: typeof AdminSurveysIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminResponsesResponseIdRoute: AdminResponsesResponseIdRoute,
  AdminSurveysSurveyIdRoute: AdminSurveysSurveyIdRoute,
  AdminSurveysNewRoute: AdminSurveysNewRoute,
  AdminIntakeIndexRoute: AdminIntakeIndexRoute,
  AdminResponsesIndexRoute: AdminResponsesIndexRoute,
  AdminSurveysIndexRoute: AdminSurveysIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
